use string keys for agent pool values
nellyk/azure-managed-cluster-capz-helm pull request #2
Opened 2024-03-14 17:33 UTC by nojnhuh

This makes it possible to structure a values override file like this without having to specify all values for each agent pool:
```yaml
agentpools:
  agentpool0:
    maxPods: 999
  agentpool1:
    mode: System
```

2024-03-14 17:34 UTC, nojnhuh commented
cc @dtzar

2024-03-14 17:42 UTC, dtzar approved these changes

2024-03-14 17:49 UTC, dtzar requested changes
@nojnhuh LGTM, just realized though we need a helm chart version bump.

2024-03-14 18:20 UTC, dtzar approved these changes

2024-03-15 14:42 UTC, merged

2024-03-15 14:49 UTC, nellyk commented
@nojnhuh Thank you!